dist: trusty
sudo: required
language: node_js
node_js: 8
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
  - node_modules/protractor/bin/webdriver-manager update
install:
  - npm install
  - npm install ionic@3 cordova -g
  - cd example
  - npm install
  - cd ..
script:
  - npm run test
  - npm run e2e
